2018-11-15 19:54:54.7990072018-11-15 19:58:22.126436b''b'Traceback (most recent call last):\n  File "/Users/Fahim/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/Users/Fahim/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "kijiji_repost_headless/__main__.py", line 195, in <module>\n    main()\n  File "kijiji_repost_headless/__main__.py", line 51, in main\n    args.function(args)\n  File "kijiji_repost_headless/__main__.py", line 134, in repost_ad\n    [data, _] = get_post_details(args.ad_file)\n  File "kijiji_repost_headless/__main__.py", line 66, in get_post_details\n    with open(ad_file, \'r\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'ad7/ad7.py\'\n'
2018-11-15 19:58:42.716404b''b'Traceback (most recent call last):\n  File "/Users/Fahim/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/Users/Fahim/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "kijiji_repost_headless/__main__.py", line 195, in <module>\n    main()\n  File "kijiji_repost_headless/__main__.py", line 51, in main\n    args.function(args)\n  File "kijiji_repost_headless/__main__.py", line 134, in repost_ad\n    [data, _] = get_post_details(args.ad_file)\n  File "kijiji_repost_headless/__main__.py", line 66, in get_post_details\n    with open(ad_file, \'r\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'ad7/ad7.py\'\n'
2018-11-15 20:00:14.4098222018-11-15 20:01:38.7499522018-11-15 20:03:19.9165962018-11-15 20:05:23.4164872018-11-15 20:08:39.190197
2018-11-15 20:12:17.5705112018-11-15 20:13:08.072944
2018-11-15 20:25:43.169067
